const appname = "eMart Seller App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password",
    anyProblem = "In case of any difficulty, contact administration",
    dashboard = "Dashboard",
    orders = "Orders",
    products = "Products",
    settings = "Settings",
    credit = "@BaabaDevs";
String unpaid = "Unpaid";
String rating = "rating";
String totalSalses = "Total Sales";
String popular = "Popular products";
const edit = "Edit";
const remove = "Remove";
const feature = "Feature";
